import { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import DefaultLayout from "@/app/[lang]/components/layout/DefaultLayout";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <DefaultLayout>{children}</DefaultLayout>
      </body>
    </html>
  );
}
